apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170118319
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170118319
    app.kubernetes.io/part-of: test-app-170118319
  name: java-quarkus-170118319
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170118319
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170118319
    spec:
      containers:
      - image: quay.io/hacdev/ournwjsy-tenant/test-app-170118319/java-quarkus-170118319@sha256:9acb9ceffdc9f17e539553bb5411b6a10318a4e149d497c532a1ce7ef13b4453
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
