apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: java-quarkus-170118319
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/ournwjsy-tenant/test-app-170118319/java-quarkus-170118319@sha256:9acb9ceffdc9f17e539553bb5411b6a10318a4e149d497c532a1ce7ef13b4453
        name: my-java-quarkus
        resources: {}
status: {}
